[runtime]
max_procs = 4

[events]
port = ":9090"
events_queue_max_size = 1000
max_buff_size_bytes = 8000

# using in case of events sorting within the fixed batch size
max_batch_size = 100 
read_timeout_ms = 500

[client]
port = ":9099"
max_buff_size_bytes = 16
send_events_queue_max_size = 100
